language: lisp
sudo: required

git:
  submodules: false

env:
  matrix:
    - LISP=sbcl

before_install:
  - echo "Changing submodule pointers to use HTTPS URL's for Travis"
  - sed -e 's#git@github.com:#https://github.com/#' -i .gitmodules
  - git submodule sync
  - echo "Updating submodules"
  - git submodule update --init --recursive

install:
  - make deps
#  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - make
  - make test
  
